/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "inverse-primary": "#bec6e0",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#89f5e7",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "primary-container": "#131b2e",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#86f2e4",
        "surface-variant": "#d3e4fe",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#45464d",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#005049",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary": "#006a61",
        "on-tertiary-container": "#b87500",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#006f66",
        "on-tertiary-fixed": "#2a1700",
        "error-container": "#ffdad6",
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "background": "#f8f9ff",
        "tertiary": "#000000",
        "outline": "#76777d",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#ffddb8",
        "error": "#ba1a1a",
        "tertiary-container": "#2a1700",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-container": "#e5eeff",
        "on-background": "#0b1c30",
        "on-secondary-fixed": "#00201d",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "surface": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "xl": "48px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "matrix-cell-gap": "2px",
        "unit": "4px",
        "container-max": "1280px"
      },
      fontFamily: {
        "h2": ["Inter"],
        "h1": ["Inter"],
        "body": ["Inter"],
        "math-caption": ["Space Grotesk"],
        "matrix-data": ["Space Grotesk"],
        "label-sm": ["Inter"]
      },
      fontSize: {
        "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "math-caption": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "matrix-data": ["18px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "label-sm": ["13px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}